#!/usr/bin/env bash
set -evuo pipefail
IFS=$'\n\t'

NAME=${1}
SLUG=${2:-$(echo "$NAME" | tr -d "\n" | tr -cs "[:alnum:]" "-" | tr "[:upper:]" "[:lower:]")}

mkdir -p "$SLUG"
cat <<EOF > "$SLUG/README.md"
# $NAME

## Abstract

## Description

## Additional Notes

EOF

git add "$SLUG/README.md"
git commit -m "Add proposal skeleton for '$NAME'."
